import { createServerFn } from "@tanstack/react-start";

import { groq } from "../sanity/http";
import { EPISODE_LIST_PROJECTION, EPISODE_PROJECTION, project } from "../sanity/projection-map";
import type { EpisodeListItem, SanityEpisode } from "./episode";

/**
 * Every Sanity read the site performs, in one module.
 *
 * **Nothing here catches.** `groq()` throws a `SanityHttpError` on a timeout, a
 * non-200, a body that is not JSON, or a body that is JSON but the wrong shape,
 * and that throw is load-bearing: it is what lets a loader emit "temporarily
 * broken" instead of "gone". Swallowing it into an empty array would render an
 * empty catalogue as though it were the truth — the single failure this design
 * exists to prevent — so a `try` block in this file would be a defect, not
 * caution.
 *
 * **Every fragment is generated by `project()`; none is hand-written.** A
 * literal projection can swap two same-typed fields (`"podbeanUrl": audioUrl`)
 * and stay green through every test while breaking the page. The alias↔source
 * pairing is decided once, in `projection-map.ts`, and pinned there.
 *
 * **Each query is exported twice, and the pairing is the point.**
 * - `…Fn` — a plain async function. For callers that are already server-only:
 *   `server.handlers.GET` (the sitemap) and anything under `scripts/`, neither
 *   of which can call a server function.
 * - the wrapper — a `createServerFn({method: "GET"})` over the same function,
 *   for route loaders.
 *
 * Loaders need the wrapper because a bare TanStack loader **also runs in the
 * browser** on a client-side navigation. That would make the Sanity CDN a
 * cross-origin browser request, requiring `thebehumancompany.ca` to be added to
 * the project's CORS allowlist — a console setting, invisible in this repo,
 * that can silently drift and take the site down on a navigation while a hard
 * refresh keeps working. A server function keeps the fetch on the server and
 * removes the requirement entirely.
 */

/** Published episodes only, newest first. The order every list surface expects. */
const PUBLISHED = `*[_type == "episode" && defined(slug.current)]`;

export const EPISODE_BY_SLUG_QUERY = `${PUBLISHED}[slug.current == $slug][0]${project(EPISODE_PROJECTION)}`;

export const EPISODE_LIST_QUERY = `${PUBLISHED} | order(publishedAt desc)${project(EPISODE_LIST_PROJECTION)}`;

/**
 * Everything the related-episode ranker needs, which is the same list shape.
 *
 * A separate export rather than a reuse of `EPISODE_LIST_QUERY` because the two
 * have different reasons to change: this one follows the ranking algorithm's
 * inputs, the other follows the directory's rendered fields. They are identical
 * today and that is a coincidence worth not encoding.
 */
export const RELATED_CANDIDATES_QUERY = EPISODE_LIST_QUERY;

/**
 * The sitemap needs the URL and the last-modified stamp, and nothing else.
 *
 * `_updatedAt` is a Sanity system field rather than an authored one, so it is
 * not in the projection map — that map governs authored content, and adding a
 * system timestamp to it would imply the schema contract should cover it.
 */
export const SITEMAP_ENTRIES_QUERY = `${PUBLISHED} | order(publishedAt desc){"slug": slug, "updatedAt": _updatedAt}`;

export interface SitemapEntry {
  slug: { current: string };
  updatedAt: string;
}

/**
 * One episode by slug, or `null` when no such episode exists.
 *
 * The `null` is a real answer, not a failure: GROQ's `[0]` on an empty result
 * set yields null, the request succeeded, and the honest response is a 404.
 * Distinguishing that from a throw is the whole of Decision L.
 */
export async function fetchEpisodeBySlugFn(slug: string): Promise<SanityEpisode | null> {
  return groq<SanityEpisode | null>(EPISODE_BY_SLUG_QUERY, { slug });
}

export async function fetchEpisodeListFn(): Promise<EpisodeListItem[]> {
  return groq<EpisodeListItem[]>(EPISODE_LIST_QUERY);
}

export async function fetchRelatedCandidatesFn(): Promise<EpisodeListItem[]> {
  return groq<EpisodeListItem[]>(RELATED_CANDIDATES_QUERY);
}

export async function fetchSitemapEntriesFn(): Promise<SitemapEntry[]> {
  return groq<SitemapEntry[]>(SITEMAP_ENTRIES_QUERY);
}

/**
 * The slug validator, exported so its behaviour is testable on its own.
 *
 * Rejects a non-string outright rather than coercing. The value arrives from a
 * URL parameter, and the query interpolates it as a GROQ *parameter* rather
 * than into the query string, so this is not the injection guard — that is
 * structural. It is a shape guard, so a malformed request fails at the boundary
 * with a clear message instead of producing a confusing empty result.
 */
export function validateSlug(data: unknown): string {
  if (typeof data !== "string" || data.length === 0) {
    throw new Error(`[podcast] expected a non-empty slug string, received ${typeof data}`);
  }
  return data;
}

export const fetchEpisodeBySlug = createServerFn({ method: "GET" })
  .validator(validateSlug)
  .handler(({ data }) => fetchEpisodeBySlugFn(data));

export const fetchEpisodeList = createServerFn({ method: "GET" }).handler(() =>
  fetchEpisodeListFn(),
);

export const fetchRelatedCandidates = createServerFn({ method: "GET" }).handler(() =>
  fetchRelatedCandidatesFn(),
);
