/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhyWeExistRouteImport } from './routes/why-we-exist'
import { Route as WhoWeAreRouteImport } from './routes/who-we-are'
import { Route as TypeSpecimenRouteImport } from './routes/type-specimen'
import { Route as TheNewHumanEraRouteImport } from './routes/the-new-human-era'
import { Route as TheHumanArchiveRouteImport } from './routes/the-human-archive'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PodcastRouteImport } from './routes/podcast'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutTheFounderRouteImport } from './routes/about-the-founder'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BeHumanAiIndexRouteImport } from './routes/be-human-ai/index'
import { Route as PodcastSlugRouteImport } from './routes/podcast_.$slug'
import { Route as BeHumanAiHumanReadinessRouteImport } from './routes/be-human-ai/human-readiness'
import { Route as BeHumanAiGovernanceRouteImport } from './routes/be-human-ai/governance'
import { Route as BeHumanAiAiStrategyRouteImport } from './routes/be-human-ai/ai-strategy'

const WhyWeExistRoute = WhyWeExistRouteImport.update({
  id: '/why-we-exist',
  path: '/why-we-exist',
  getParentRoute: () => rootRouteImport,
} as any)
const WhoWeAreRoute = WhoWeAreRouteImport.update({
  id: '/who-we-are',
  path: '/who-we-are',
  getParentRoute: () => rootRouteImport,
} as any)
const TypeSpecimenRoute = TypeSpecimenRouteImport.update({
  id: '/type-specimen',
  path: '/type-specimen',
  getParentRoute: () => rootRouteImport,
} as any)
const TheNewHumanEraRoute = TheNewHumanEraRouteImport.update({
  id: '/the-new-human-era',
  path: '/the-new-human-era',
  getParentRoute: () => rootRouteImport,
} as any)
const TheHumanArchiveRoute = TheHumanArchiveRouteImport.update({
  id: '/the-human-archive',
  path: '/the-human-archive',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PodcastRoute = PodcastRouteImport.update({
  id: '/podcast',
  path: '/podcast',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutTheFounderRoute = AboutTheFounderRouteImport.update({
  id: '/about-the-founder',
  path: '/about-the-founder',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BeHumanAiIndexRoute = BeHumanAiIndexRouteImport.update({
  id: '/be-human-ai/',
  path: '/be-human-ai/',
  getParentRoute: () => rootRouteImport,
} as any)
const PodcastSlugRoute = PodcastSlugRouteImport.update({
  id: '/podcast_/$slug',
  path: '/podcast/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BeHumanAiHumanReadinessRoute = BeHumanAiHumanReadinessRouteImport.update({
  id: '/be-human-ai/human-readiness',
  path: '/be-human-ai/human-readiness',
  getParentRoute: () => rootRouteImport,
} as any)
const BeHumanAiGovernanceRoute = BeHumanAiGovernanceRouteImport.update({
  id: '/be-human-ai/governance',
  path: '/be-human-ai/governance',
  getParentRoute: () => rootRouteImport,
} as any)
const BeHumanAiAiStrategyRoute = BeHumanAiAiStrategyRouteImport.update({
  id: '/be-human-ai/ai-strategy',
  path: '/be-human-ai/ai-strategy',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about-the-founder': typeof AboutTheFounderRoute
  '/contact': typeof ContactRoute
  '/podcast': typeof PodcastRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/the-human-archive': typeof TheHumanArchiveRoute
  '/the-new-human-era': typeof TheNewHumanEraRoute
  '/type-specimen': typeof TypeSpecimenRoute
  '/who-we-are': typeof WhoWeAreRoute
  '/why-we-exist': typeof WhyWeExistRoute
  '/be-human-ai/ai-strategy': typeof BeHumanAiAiStrategyRoute
  '/be-human-ai/governance': typeof BeHumanAiGovernanceRoute
  '/be-human-ai/human-readiness': typeof BeHumanAiHumanReadinessRoute
  '/podcast/$slug': typeof PodcastSlugRoute
  '/be-human-ai/': typeof BeHumanAiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about-the-founder': typeof AboutTheFounderRoute
  '/contact': typeof ContactRoute
  '/podcast': typeof PodcastRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/the-human-archive': typeof TheHumanArchiveRoute
  '/the-new-human-era': typeof TheNewHumanEraRoute
  '/type-specimen': typeof TypeSpecimenRoute
  '/who-we-are': typeof WhoWeAreRoute
  '/why-we-exist': typeof WhyWeExistRoute
  '/be-human-ai/ai-strategy': typeof BeHumanAiAiStrategyRoute
  '/be-human-ai/governance': typeof BeHumanAiGovernanceRoute
  '/be-human-ai/human-readiness': typeof BeHumanAiHumanReadinessRoute
  '/podcast/$slug': typeof PodcastSlugRoute
  '/be-human-ai': typeof BeHumanAiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about-the-founder': typeof AboutTheFounderRoute
  '/contact': typeof ContactRoute
  '/podcast': typeof PodcastRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/the-human-archive': typeof TheHumanArchiveRoute
  '/the-new-human-era': typeof TheNewHumanEraRoute
  '/type-specimen': typeof TypeSpecimenRoute
  '/who-we-are': typeof WhoWeAreRoute
  '/why-we-exist': typeof WhyWeExistRoute
  '/be-human-ai/ai-strategy': typeof BeHumanAiAiStrategyRoute
  '/be-human-ai/governance': typeof BeHumanAiGovernanceRoute
  '/be-human-ai/human-readiness': typeof BeHumanAiHumanReadinessRoute
  '/podcast_/$slug': typeof PodcastSlugRoute
  '/be-human-ai/': typeof BeHumanAiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/about-the-founder'
    | '/contact'
    | '/podcast'
    | '/sitemap.xml'
    | '/the-human-archive'
    | '/the-new-human-era'
    | '/type-specimen'
    | '/who-we-are'
    | '/why-we-exist'
    | '/be-human-ai/ai-strategy'
    | '/be-human-ai/governance'
    | '/be-human-ai/human-readiness'
    | '/podcast/$slug'
    | '/be-human-ai/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/about-the-founder'
    | '/contact'
    | '/podcast'
    | '/sitemap.xml'
    | '/the-human-archive'
    | '/the-new-human-era'
    | '/type-specimen'
    | '/who-we-are'
    | '/why-we-exist'
    | '/be-human-ai/ai-strategy'
    | '/be-human-ai/governance'
    | '/be-human-ai/human-readiness'
    | '/podcast/$slug'
    | '/be-human-ai'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/about-the-founder'
    | '/contact'
    | '/podcast'
    | '/sitemap.xml'
    | '/the-human-archive'
    | '/the-new-human-era'
    | '/type-specimen'
    | '/who-we-are'
    | '/why-we-exist'
    | '/be-human-ai/ai-strategy'
    | '/be-human-ai/governance'
    | '/be-human-ai/human-readiness'
    | '/podcast_/$slug'
    | '/be-human-ai/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AboutTheFounderRoute: typeof AboutTheFounderRoute
  ContactRoute: typeof ContactRoute
  PodcastRoute: typeof PodcastRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TheHumanArchiveRoute: typeof TheHumanArchiveRoute
  TheNewHumanEraRoute: typeof TheNewHumanEraRoute
  TypeSpecimenRoute: typeof TypeSpecimenRoute
  WhoWeAreRoute: typeof WhoWeAreRoute
  WhyWeExistRoute: typeof WhyWeExistRoute
  BeHumanAiAiStrategyRoute: typeof BeHumanAiAiStrategyRoute
  BeHumanAiGovernanceRoute: typeof BeHumanAiGovernanceRoute
  BeHumanAiHumanReadinessRoute: typeof BeHumanAiHumanReadinessRoute
  PodcastSlugRoute: typeof PodcastSlugRoute
  BeHumanAiIndexRoute: typeof BeHumanAiIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/why-we-exist': {
      id: '/why-we-exist'
      path: '/why-we-exist'
      fullPath: '/why-we-exist'
      preLoaderRoute: typeof WhyWeExistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/who-we-are': {
      id: '/who-we-are'
      path: '/who-we-are'
      fullPath: '/who-we-are'
      preLoaderRoute: typeof WhoWeAreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/type-specimen': {
      id: '/type-specimen'
      path: '/type-specimen'
      fullPath: '/type-specimen'
      preLoaderRoute: typeof TypeSpecimenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/the-new-human-era': {
      id: '/the-new-human-era'
      path: '/the-new-human-era'
      fullPath: '/the-new-human-era'
      preLoaderRoute: typeof TheNewHumanEraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/the-human-archive': {
      id: '/the-human-archive'
      path: '/the-human-archive'
      fullPath: '/the-human-archive'
      preLoaderRoute: typeof TheHumanArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcast': {
      id: '/podcast'
      path: '/podcast'
      fullPath: '/podcast'
      preLoaderRoute: typeof PodcastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-the-founder': {
      id: '/about-the-founder'
      path: '/about-the-founder'
      fullPath: '/about-the-founder'
      preLoaderRoute: typeof AboutTheFounderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/be-human-ai/': {
      id: '/be-human-ai/'
      path: '/be-human-ai'
      fullPath: '/be-human-ai/'
      preLoaderRoute: typeof BeHumanAiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcast_/$slug': {
      id: '/podcast_/$slug'
      path: '/podcast/$slug'
      fullPath: '/podcast/$slug'
      preLoaderRoute: typeof PodcastSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/be-human-ai/human-readiness': {
      id: '/be-human-ai/human-readiness'
      path: '/be-human-ai/human-readiness'
      fullPath: '/be-human-ai/human-readiness'
      preLoaderRoute: typeof BeHumanAiHumanReadinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/be-human-ai/governance': {
      id: '/be-human-ai/governance'
      path: '/be-human-ai/governance'
      fullPath: '/be-human-ai/governance'
      preLoaderRoute: typeof BeHumanAiGovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/be-human-ai/ai-strategy': {
      id: '/be-human-ai/ai-strategy'
      path: '/be-human-ai/ai-strategy'
      fullPath: '/be-human-ai/ai-strategy'
      preLoaderRoute: typeof BeHumanAiAiStrategyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AboutTheFounderRoute: AboutTheFounderRoute,
  ContactRoute: ContactRoute,
  PodcastRoute: PodcastRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TheHumanArchiveRoute: TheHumanArchiveRoute,
  TheNewHumanEraRoute: TheNewHumanEraRoute,
  TypeSpecimenRoute: TypeSpecimenRoute,
  WhoWeAreRoute: WhoWeAreRoute,
  WhyWeExistRoute: WhyWeExistRoute,
  BeHumanAiAiStrategyRoute: BeHumanAiAiStrategyRoute,
  BeHumanAiGovernanceRoute: BeHumanAiGovernanceRoute,
  BeHumanAiHumanReadinessRoute: BeHumanAiHumanReadinessRoute,
  PodcastSlugRoute: PodcastSlugRoute,
  BeHumanAiIndexRoute: BeHumanAiIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
