/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TheNewHumanEraRouteImport } from './routes/the-new-human-era'
import { Route as TheHumanArchiveRouteImport } from './routes/the-human-archive'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PodcastRouteImport } from './routes/podcast'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BeHumanAiRouteImport } from './routes/be-human-ai'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const TheNewHumanEraRoute = TheNewHumanEraRouteImport.update({
  id: '/the-new-human-era',
  path: '/the-new-human-era',
  getParentRoute: () => rootRouteImport,
} as any)
const TheHumanArchiveRoute = TheHumanArchiveRouteImport.update({
  id: '/the-human-archive',
  path: '/the-human-archive',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PodcastRoute = PodcastRouteImport.update({
  id: '/podcast',
  path: '/podcast',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BeHumanAiRoute = BeHumanAiRouteImport.update({
  id: '/be-human-ai',
  path: '/be-human-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/be-human-ai': typeof BeHumanAiRoute
  '/contact': typeof ContactRoute
  '/podcast': typeof PodcastRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/the-human-archive': typeof TheHumanArchiveRoute
  '/the-new-human-era': typeof TheNewHumanEraRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/be-human-ai': typeof BeHumanAiRoute
  '/contact': typeof ContactRoute
  '/podcast': typeof PodcastRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/the-human-archive': typeof TheHumanArchiveRoute
  '/the-new-human-era': typeof TheNewHumanEraRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/be-human-ai': typeof BeHumanAiRoute
  '/contact': typeof ContactRoute
  '/podcast': typeof PodcastRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/the-human-archive': typeof TheHumanArchiveRoute
  '/the-new-human-era': typeof TheNewHumanEraRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/be-human-ai'
    | '/contact'
    | '/podcast'
    | '/sitemap.xml'
    | '/the-human-archive'
    | '/the-new-human-era'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/be-human-ai'
    | '/contact'
    | '/podcast'
    | '/sitemap.xml'
    | '/the-human-archive'
    | '/the-new-human-era'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/be-human-ai'
    | '/contact'
    | '/podcast'
    | '/sitemap.xml'
    | '/the-human-archive'
    | '/the-new-human-era'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BeHumanAiRoute: typeof BeHumanAiRoute
  ContactRoute: typeof ContactRoute
  PodcastRoute: typeof PodcastRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TheHumanArchiveRoute: typeof TheHumanArchiveRoute
  TheNewHumanEraRoute: typeof TheNewHumanEraRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/the-new-human-era': {
      id: '/the-new-human-era'
      path: '/the-new-human-era'
      fullPath: '/the-new-human-era'
      preLoaderRoute: typeof TheNewHumanEraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/the-human-archive': {
      id: '/the-human-archive'
      path: '/the-human-archive'
      fullPath: '/the-human-archive'
      preLoaderRoute: typeof TheHumanArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcast': {
      id: '/podcast'
      path: '/podcast'
      fullPath: '/podcast'
      preLoaderRoute: typeof PodcastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/be-human-ai': {
      id: '/be-human-ai'
      path: '/be-human-ai'
      fullPath: '/be-human-ai'
      preLoaderRoute: typeof BeHumanAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BeHumanAiRoute: BeHumanAiRoute,
  ContactRoute: ContactRoute,
  PodcastRoute: PodcastRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TheHumanArchiveRoute: TheHumanArchiveRoute,
  TheNewHumanEraRoute: TheNewHumanEraRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
